idle_bg = "#29263c"
idle_fg = "#edecee"
info_bg = "#61ffca"
info_fg = "#15141b"
good_bg = "#82e2ff"
good_fg = "#15141b"
warning_bg = "#ff6767"
warning_fg = "#15141b"
critical_bg = "#ff6767"
critical_fg = "#15141b"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
